version: '3.0'
services:
  node:
    image: minhtranin/swtest:node1
    ports:
      - 8085:8085
    networks:
      - nw1

    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure
  golang:
    image: minhtranin/swtest:node2
    ports:
      - 8086:8086
    networks:
      - nw2

    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure
networks:
  nw1:
  nw2:
    driver: overlay
volumes:
  vl1:
    driver: local
    name: vl
    driver_opts:
      type: none
      divice: /home/
      o: bind
